-- Add description and content columns to contrats table
ALTER TABLE public.contrats
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS content text;

-- Add comment for documentation
COMMENT ON COLUMN public.contrats.description IS 'Short description or summary of the contract';
COMMENT ON COLUMN public.contrats.content IS 'Full contract text content generated by AI or template';
